spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dooribun
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database: postgresql

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: dooribun-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false